# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="agnoster"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh


# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# ZSH Syntax Highlighting
source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# ZSH Auto Suggestions
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

# alias hc='history -p && rm ~/.zsh_history && history -p'
# alias kexit='hc && exit'
# https://github.com/agnoster/agnoster-zsh-theme/issues/19#issuecomment-917635601
prompt_dir() {
  prompt_segment blue $CURRENT_FG '%c'
}

# Brew Related
eval "$(/opt/homebrew/bin/brew shellenv)"
alias ubrew='brew upgrade $(brew list)'
alias zbash="source ~/.zshrc"

# Node Version Manager Related
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion


# Changing Directories
alias mine='cd ~/Documents/Dev/GitHub/'
alias github='cd ~/Documents/Dev/GitHub/gh/'

# Simple Tools
alias nf='neofetch'
alias ntest='ping www.google.com'
alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'
alias ainstall='arch -arm64 brew install'


# Python Related
python_libs="$HOME/Library/Python/3.9/bin"
export PATH="$python_libs:${PATH}"
alias py='python3'
alias pip='pip3'
alias venv='virtualenv'
alias seba="source env/bin/activate"
alias alrev='alembic revision --autogenerate -m'
alias alup='alembic upgrade head'
alias astart='uvicorn app.main:app --reload'
alias genreq='py -m pip freeze > requirements.txt'

# XCode Related
alias repod='pod deintegrate && rm Podfile.lock && pod install'
alias bump='xcrun agvtool next-version -all'


# Git Related
alias setlocal='git config --local user.name "KamalDGRT" && git config --local user.email "kamaldgrt@gmail.com"'
alias clone='gh repo clone'
alias showGitUser='(
echo "Local:"
echo "------"
echo "Name : "
git config --local user.name
echo ""
echo "Email :"
git config --local user.email
echo ""

echo "Global :"
echo "--------"
echo "Name : "
git config --global user.name
echo ""
echo "Email :"
git config --global user.email
)'

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
# export SDKMAN_DIR="$HOME/.sdkman"
# [[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

# Youtube DL
alias ymp4="yt-dlp -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio' --merge-output-format mp4 "
alias ytmp3='yt-dlp -f bestaudio -x --audio-format mp3'


# # If you need to have mysql-client first in your PATH, run:
# export PATH="/opt/homebrew/opt/mysql-client/bin:$PATH"

# # For compilers to find mysql-client you may need to set:



# If you need to have bison first in your PATH, run:
export PATH="/opt/homebrew/opt/bison/bin:$PATH"

# For compilers to find bison you may need to set:
export LDFLAGS="-L/opt/homebrew/opt/bison/lib"

# # For pkg-config to find mysql-client you may need to set:
export PKG_CONFIG_PATH=" /opt/homebrew/opt/mariadb/lib/pkgconfig "

# openssl compilation flags
export LDFLAGS="-L$(brew --prefix openssl)/lib"
export CPPFLAGS="-I$(brew --prefix openssl)/include"

export JAVA_HOME='/Applications/Android Studio.app/Contents/jbr/Contents/Home'
export PATH=$JAVA_HOME/bin:$PATH


# Android Sdk tools
export ANDROID_HOME=${HOME}/Library/Android/sdk
export PATH=${HOME}/Library/Android/sdk/tools/bin:$PATH
export PATH=${HOME}/Library/Android/sdk/platform-tools:$PATH

# Flutter binaries
export PATH=${HOME}/Documents/Dev/flutter/bin:$PATH
